on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup SSH Deploy Keys
      run: |
        mkdir -p ~/.ssh
        echo '${{ secrets.PRIVKEY }}' > ./key
        chmod 600 ./key
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
  
    - name: Deploy
      run: |
        scp -i ./key -r ./* root@8.218.58.237:/home/wwwroot/seati-storage